# coding: utf-8

"""
    ORY Hydra

    Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here.  # noqa: E501

    The version of the OpenAPI document: v1.10.6
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import ory_hydra_client
from ory_hydra_client.models.well_known import WellKnown  # noqa: E501
from ory_hydra_client.rest import ApiException

class TestWellKnown(unittest.TestCase):
    """WellKnown unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test WellKnown
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = ory_hydra_client.models.well_known.WellKnown()  # noqa: E501
        if include_optional :
            return WellKnown(
                authorization_endpoint = 'https://playground.ory.sh/ory-hydra/public/oauth2/auth', 
                backchannel_logout_session_supported = True, 
                backchannel_logout_supported = True, 
                claims_parameter_supported = True, 
                claims_supported = [
                    '0'
                    ], 
                code_challenge_methods_supported = [
                    '0'
                    ], 
                end_session_endpoint = '0', 
                frontchannel_logout_session_supported = True, 
                frontchannel_logout_supported = True, 
                grant_types_supported = [
                    '0'
                    ], 
                id_token_signing_alg_values_supported = [
                    '0'
                    ], 
                issuer = 'https://playground.ory.sh/ory-hydra/public/', 
                jwks_uri = 'https://playground.ory.sh/ory-hydra/public/.well-known/jwks.json', 
                registration_endpoint = 'https://playground.ory.sh/ory-hydra/admin/client', 
                request_object_signing_alg_values_supported = [
                    '0'
                    ], 
                request_parameter_supported = True, 
                request_uri_parameter_supported = True, 
                require_request_uri_registration = True, 
                response_modes_supported = [
                    '0'
                    ], 
                response_types_supported = [
                    '0'
                    ], 
                revocation_endpoint = '0', 
                scopes_supported = [
                    '0'
                    ], 
                subject_types_supported = [
                    '0'
                    ], 
                token_endpoint = 'https://playground.ory.sh/ory-hydra/public/oauth2/token', 
                token_endpoint_auth_methods_supported = [
                    '0'
                    ], 
                userinfo_endpoint = '0', 
                userinfo_signing_alg_values_supported = [
                    '0'
                    ]
            )
        else :
            return WellKnown(
                authorization_endpoint = 'https://playground.ory.sh/ory-hydra/public/oauth2/auth',
                id_token_signing_alg_values_supported = [
                    '0'
                    ],
                issuer = 'https://playground.ory.sh/ory-hydra/public/',
                jwks_uri = 'https://playground.ory.sh/ory-hydra/public/.well-known/jwks.json',
                response_types_supported = [
                    '0'
                    ],
                subject_types_supported = [
                    '0'
                    ],
                token_endpoint = 'https://playground.ory.sh/ory-hydra/public/oauth2/token',
        )

    def testWellKnown(self):
        """Test WellKnown"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
