# coding: utf-8

"""
    ORY Hydra

    Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here.  # noqa: E501

    The version of the OpenAPI document: v1.10.6
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import ory_hydra_client
from ory_hydra_client.models.accept_consent_request import AcceptConsentRequest  # noqa: E501
from ory_hydra_client.rest import ApiException

class TestAcceptConsentRequest(unittest.TestCase):
    """AcceptConsentRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test AcceptConsentRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = ory_hydra_client.models.accept_consent_request.AcceptConsentRequest()  # noqa: E501
        if include_optional :
            return AcceptConsentRequest(
                grant_access_token_audience = [
                    '0'
                    ], 
                grant_scope = [
                    '0'
                    ], 
                handled_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                remember = True, 
                remember_for = 56, 
                session = ory_hydra_client.models.used_to_pass_session_data_to_a_consent_request/.Used to pass session data to a consent request.(
                    access_token = ory_hydra_client.models.access_token.access_token(), 
                    id_token = ory_hydra_client.models.id_token.id_token(), )
            )
        else :
            return AcceptConsentRequest(
        )

    def testAcceptConsentRequest(self):
        """Test AcceptConsentRequest"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
