# coding: utf-8

"""
    ORY Hydra

    Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here.  # noqa: E501

    The version of the OpenAPI document: v1.10.6
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import ory_hydra_client
from ory_hydra_client.models.json_error import JsonError  # noqa: E501
from ory_hydra_client.rest import ApiException

class TestJsonError(unittest.TestCase):
    """JsonError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test JsonError
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = ory_hydra_client.models.json_error.JsonError()  # noqa: E501
        if include_optional :
            return JsonError(
                error = 'The requested resource could not be found', 
                error_debug = 'The database adapter was unable to find the element', 
                error_description = 'Object with ID 12345 does not exist', 
                status_code = 404
            )
        else :
            return JsonError(
        )

    def testJsonError(self):
        """Test JsonError"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
