# coding: utf-8

"""
    ORY Hydra

    Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here.  # noqa: E501

    The version of the OpenAPI document: v1.10.6
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import ory_hydra_client
from ory_hydra_client.models.volume import Volume  # noqa: E501
from ory_hydra_client.rest import ApiException

class TestVolume(unittest.TestCase):
    """Volume unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Volume
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = ory_hydra_client.models.volume.Volume()  # noqa: E501
        if include_optional :
            return Volume(
                created_at = '0', 
                driver = '0', 
                labels = {
                    'key' : '0'
                    }, 
                mountpoint = '0', 
                name = '0', 
                options = {
                    'key' : '0'
                    }, 
                scope = '0', 
                status = None, 
                usage_data = ory_hydra_client.models.volume_usage_data.VolumeUsageData(
                    ref_count = 56, 
                    size = 56, )
            )
        else :
            return Volume(
                driver = '0',
                labels = {
                    'key' : '0'
                    },
                mountpoint = '0',
                name = '0',
                options = {
                    'key' : '0'
                    },
                scope = '0',
        )

    def testVolume(self):
        """Test Volume"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
