# coding: utf-8

"""
    ORY Hydra

    Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here.  # noqa: E501

    The version of the OpenAPI document: v1.10.6
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import ory_hydra_client
from ory_hydra_client.models.o_auth2_token_introspection import OAuth2TokenIntrospection  # noqa: E501
from ory_hydra_client.rest import ApiException

class TestOAuth2TokenIntrospection(unittest.TestCase):
    """OAuth2TokenIntrospection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test OAuth2TokenIntrospection
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = ory_hydra_client.models.o_auth2_token_introspection.OAuth2TokenIntrospection()  # noqa: E501
        if include_optional :
            return OAuth2TokenIntrospection(
                active = True, 
                aud = [
                    '0'
                    ], 
                client_id = '0', 
                exp = 56, 
                ext = None, 
                iat = 56, 
                iss = '0', 
                nbf = 56, 
                obfuscated_subject = '0', 
                scope = '0', 
                sub = '0', 
                token_type = '0', 
                token_use = '0', 
                username = '0'
            )
        else :
            return OAuth2TokenIntrospection(
                active = True,
        )

    def testOAuth2TokenIntrospection(self):
        """Test OAuth2TokenIntrospection"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
