# coding: utf-8

"""
    ORY Hydra

    Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here.  # noqa: E501

    The version of the OpenAPI document: v1.10.6
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import ory_hydra_client
from ory_hydra_client.models.flush_inactive_o_auth2_tokens_request import FlushInactiveOAuth2TokensRequest  # noqa: E501
from ory_hydra_client.rest import ApiException

class TestFlushInactiveOAuth2TokensRequest(unittest.TestCase):
    """FlushInactiveOAuth2TokensRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test FlushInactiveOAuth2TokensRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = ory_hydra_client.models.flush_inactive_o_auth2_tokens_request.FlushInactiveOAuth2TokensRequest()  # noqa: E501
        if include_optional :
            return FlushInactiveOAuth2TokensRequest(
                not_after = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else :
            return FlushInactiveOAuth2TokensRequest(
        )

    def testFlushInactiveOAuth2TokensRequest(self):
        """Test FlushInactiveOAuth2TokensRequest"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
