# coding: utf-8

"""
    ORY Hydra

    Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here.  # noqa: E501

    The version of the OpenAPI document: v1.10.6
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import ory_hydra_client
from ory_hydra_client.models.userinfo_response import UserinfoResponse  # noqa: E501
from ory_hydra_client.rest import ApiException

class TestUserinfoResponse(unittest.TestCase):
    """UserinfoResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test UserinfoResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = ory_hydra_client.models.userinfo_response.UserinfoResponse()  # noqa: E501
        if include_optional :
            return UserinfoResponse(
                birthdate = '0', 
                email = '0', 
                email_verified = True, 
                family_name = '0', 
                gender = '0', 
                given_name = '0', 
                locale = '0', 
                middle_name = '0', 
                name = '0', 
                nickname = '0', 
                phone_number = '0', 
                phone_number_verified = True, 
                picture = '0', 
                preferred_username = '0', 
                profile = '0', 
                sub = '0', 
                updated_at = 56, 
                website = '0', 
                zoneinfo = '0'
            )
        else :
            return UserinfoResponse(
        )

    def testUserinfoResponse(self):
        """Test UserinfoResponse"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
