# coding: utf-8

"""
    ORY Hydra

    Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here.  # noqa: E501

    The version of the OpenAPI document: v1.10.6
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from ory_hydra_client.configuration import Configuration


class PatchDocument(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        '_from': 'str',
        'op': 'str',
        'path': 'str',
        'value': 'object'
    }

    attribute_map = {
        '_from': 'from',
        'op': 'op',
        'path': 'path',
        'value': 'value'
    }

    def __init__(self, _from=None, op=None, path=None, value=None, local_vars_configuration=None):  # noqa: E501
        """PatchDocument - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self.__from = None
        self._op = None
        self._path = None
        self._value = None
        self.discriminator = None

        if _from is not None:
            self._from = _from
        self.op = op
        self.path = path
        if value is not None:
            self.value = value

    @property
    def _from(self):
        """Gets the _from of this PatchDocument.  # noqa: E501

        A JSON-pointer  # noqa: E501

        :return: The _from of this PatchDocument.  # noqa: E501
        :rtype: str
        """
        return self.__from

    @_from.setter
    def _from(self, _from):
        """Sets the _from of this PatchDocument.

        A JSON-pointer  # noqa: E501

        :param _from: The _from of this PatchDocument.  # noqa: E501
        :type: str
        """

        self.__from = _from

    @property
    def op(self):
        """Gets the op of this PatchDocument.  # noqa: E501

        The operation to be performed  # noqa: E501

        :return: The op of this PatchDocument.  # noqa: E501
        :rtype: str
        """
        return self._op

    @op.setter
    def op(self, op):
        """Sets the op of this PatchDocument.

        The operation to be performed  # noqa: E501

        :param op: The op of this PatchDocument.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and op is None:  # noqa: E501
            raise ValueError("Invalid value for `op`, must not be `None`")  # noqa: E501

        self._op = op

    @property
    def path(self):
        """Gets the path of this PatchDocument.  # noqa: E501

        A JSON-pointer  # noqa: E501

        :return: The path of this PatchDocument.  # noqa: E501
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path):
        """Sets the path of this PatchDocument.

        A JSON-pointer  # noqa: E501

        :param path: The path of this PatchDocument.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and path is None:  # noqa: E501
            raise ValueError("Invalid value for `path`, must not be `None`")  # noqa: E501

        self._path = path

    @property
    def value(self):
        """Gets the value of this PatchDocument.  # noqa: E501

        The value to be used within the operations  # noqa: E501

        :return: The value of this PatchDocument.  # noqa: E501
        :rtype: object
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this PatchDocument.

        The value to be used within the operations  # noqa: E501

        :param value: The value of this PatchDocument.  # noqa: E501
        :type: object
        """

        self._value = value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PatchDocument):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PatchDocument):
            return True

        return self.to_dict() != other.to_dict()
